# Generated by Django 5.1.1 on 2024-12-10 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('ability_id', models.IntegerField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=50)),
                ('name_zhHans', models.CharField(max_length=50)),
                ('flavor_text_zhHans', models.TextField()),
                ('memo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=100)),
                ('name_zhHans', models.CharField(max_length=50)),
                ('sprites_url', models.TextField()),
                ('flavor_text_zhHans', models.TextField()),
                ('memo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MovesDamageClasses',
            fields=[
                ('damage_id', models.IntegerField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=50)),
                ('name_zhHans', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MovesEffect',
            fields=[
                ('effect_id', models.IntegerField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=50)),
                ('name_zhHans', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MovesTarget',
            fields=[
                ('target_id', models.IntegerField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=50)),
                ('name_zhHans', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('pokemon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=50)),
                ('name_zhHans', models.CharField(max_length=50)),
                ('species_id', models.IntegerField()),
                ('sprites_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonAbilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.IntegerField()),
                ('ability_id', models.IntegerField()),
                ('is_hidden', models.BooleanField()),
                ('slot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonSpecies',
            fields=[
                ('species_id', models.IntegerField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=50)),
                ('name_zhHans', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.IntegerField()),
                ('type_id', models.IntegerField()),
                ('slot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('stat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=50)),
                ('name_zhHans', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=50)),
                ('name_zhHans', models.CharField(max_length=50)),
                ('sprites_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('move_id', models.IntegerField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=50)),
                ('name_zhHans', models.CharField(max_length=50)),
                ('power', models.IntegerField()),
                ('pp', models.IntegerField()),
                ('accuracy', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('effect_chance', models.IntegerField()),
                ('damage_classes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.movesdamageclasses')),
                ('effect_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.moveseffect')),
                ('target_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.movestarget')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.type')),
            ],
        ),
        migrations.CreateModel(
            name='Natures',
            fields=[
                ('nature_id', models.IntegerField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=50)),
                ('name_zhHans', models.CharField(max_length=50)),
                ('decrease_stat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decrease_stat', to='search.stats')),
                ('increase_stat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='increase_stat', to='search.stats')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.IntegerField()),
                ('collect_time', models.DateField()),
                ('userate', models.FloatField()),
                ('item_userate', models.FloatField()),
                ('nature_userate', models.FloatField()),
                ('efffort_values', models.TextField()),
                ('effort_userates', models.TextField()),
                ('tera_type_userate', models.FloatField()),
                ('ability_userate', models.FloatField()),
                ('moves_userates', models.TextField()),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.abilities')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.items')),
                ('moves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.moves')),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.natures')),
                ('tera_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.type')),
            ],
        ),
    ]
